### ISSUE TITLE
How to update device token after analytics is initialized?

### ISSUE THREAD

**Issue by ggirotto** [segmentio/analytics_flutter#100]
In this PR https://github.com/segmentio/analytics_flutter/pull/73 it seems that you guys added a new property to `Configuration` class which is `token`, but what happens if the device token is only acquired after the analytics was already initialized? Should we create a new instance of the analytics to replace the old now or use the solution proposed on this issue https://github.com/segmentio/analytics_flutter/issues/29?

**Comment by edsonjab** [comment]
hi @ggirotto we add token to change on any time on the execution process, to update the context once the Analytics was initialized you need to use the proposed solution because you can use the same instance of Analytics was declared at the beginning to update the context.
