### ISSUE TITLE
[plugin_firebase] Needs updating to support new major versions of Firebase dependencies

### ISSUE THREAD

**Issue by QuirijnGB** [segmentio/analytics_flutter#101]
Current version of `segment_analytics_plugin_firebase` only supports the previous major releases of the firebase dependencies blocking the our app from updating our own dependencies
```
  firebase_analytics: ^10.1.0
  firebase_core: ^2.7.0
```

Newer versions are available:
```
  firebase_analytics: ^11.3.2
  firebase_core: ^3.5.0
```

**Comment by edsonjab** [comment]
Hi @QuirijnGB, thank you for your report, we start working into this.

**Comment by 0aps** [comment]
it would be awesome to get this MR merged and published, it's currently holding us for upgrading.
