### ISSUE TITLE
Use of plugin as a singleton

### ISSUE THREAD

**Issue by DebkanchanSamadder** [segmentio/analytics_flutter#11]
In this current form, this plugin requires that the user create an analytics instance and use it throughout the app, which requires either 
- using a global `analytics` variable (which is not recommended and is an antipattern) 
- wrapping it with a singleton class(inconvenient) 
- dependency injecting it (using prop drilling or state management solutions).

Rather than this, it would be beneficial if it was a singleton instance like `Segment.Instance` just like how Firebase analytics does it with `FirebaseAnalytics.Instance`

**Comment by edsonjab** [comment]
Hi @DebkanchanSamadder  thank you for your report, we start looking into this and we will check your PR.

**Comment by oscb** [comment]
Not doing singletons is part of the design of the library to enable support for multiple clients by default. This is better to handle per app at the moment.
