### ISSUE TITLE
Cannot add custom value on GroupTraits

### ISSUE THREAD

**Issue by Jeonguk-ninehire** [segmentio/analytics_flutter#13]
Cannot add custom value on GroupTraits.

Because it missed custom value when merging userInfo.groupTraits and groupEvent.traits on InjectUserInfo.execute().

Also it is need to fix document about GroupTrait customs value.

Custom value can be set by cascade notation like below

```
final groupTraits = GroupTraits()
      ..custom = {
        'custom_key': 'custom_value',
      };
```

**Comment by edsonjab** [comment]
Hi @Jeonguk-ninehire  thank you for your report, we start looking into this.
