### ISSUE TITLE
Could not find device id even after mentioning collectDeviceId to true.

### ISSUE THREAD

**Issue by praveenpillimovieme** [segmentio/analytics_flutter#15]
Hi Team, Great work on the package. I have mentioned collectDeviceId to true in my configuration and able to track and identify the events. But for some reason the deviceid is not coming through in the identification or tracks. Am I missing anything?

**Comment by edsonjab** [comment]
hi @praveenpillimovieme thanks for your comments. Are you using this property on iOS device? because only works on Android devices.

We mention this on the [README](https://github.com/segmentio/analytics_flutter#client-options)
