### ISSUE TITLE
Send data to Firebase in Device Mode

### ISSUE THREAD

**Issue by danceballos** [segmentio/analytics_flutter#2]
We are trying to send data to a Firebase destination, we followed the instructions in this training video: 
https://university.segment.com/connection-modes/571390

But it is based on iOS and Android code, also, the "Additinal Settings" tab on the Firebase destination states the following: 

> Additional Setup
> To use this integration, you'll need to include their library by adding these lines to your dependency config:
> 
> For [iOS](https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/#packaging-destinations-using-device-mode):
> First add this to your Podfile:
> 
> 1
>  pod ‘Segment-Firebase’ 
> After adding the dependency, you must import the integration
> 
> 1
> #import <Segment-Firebase/SEGFirebaseIntegrationFactory.h>
> Finally, register it with the Segment SDK
> 
> 1
> [config use:[SEGFirebaseIntegrationFactory instance]];
> For [Android](https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/#packaging-sdks-for-device-mode-destinations):
> First add this to your Gradle:
> 
> 1
> compile 'com.segment.analytics.android.integrations.firebase:+'
> Add Google Services to your project-level Gradle
> 
> 1
> classpath 'com.google.gms:google-services:3.1.0'
> Apply Google Services at the very bottom of your app-level Gradle
> 
> 1
> apply plugin: 'com.google.gms.google-services'
> Add Google's repo to the `allprojects` section of your project-level Gradle
> 
> 1
> maven { url 'https://maven.google.com' }
> Add Firebase's google-services.json file to your project's `app` directory
> 
> 1
> google-services.json
> Finally, register the integration with the Segment SDK
> 
> 1
> builder.use(FirebaseIntegration.FACTORY);
> As you can see there is no indication as of how to do this on flutter. 

Any guide on how to do it? 

PS. We are searching for data in Firebase but there is no data there either.

**Comment by oscb** [comment]
@danceballos you don't need to do all of that, that's just for Native applications. I'll follow up with the Documentation team to add more details in mobile for other non-native offerings.

I recommend following these instructions instead: https://github.com/segmentio/analytics_flutter/tree/main/packages/plugins/plugin_firebase#installation

The key part is to follow the Firebase instructions for Flutter in particular
