### ISSUE TITLE
When this library is going to be released to pub.dev?

### ISSUE THREAD

**Issue by kuznetsov-from-wonderland** [segmentio/analytics_flutter#23]
When this library is going to be released to pub.dev?

**Comment by czypnt** [comment]
Same question curious if we can use via pub.dev

**Comment by oscb** [comment]
We will be releasing this to [pub.dev](http://pub.dev/) and public beta later this month!

**Comment by oscb** [comment]
The library now publicly available in [Pub.dev](http://pub.dev/packages/segment_analytics) as `segment_analytics`!
