### ISSUE TITLE
Set push token

### ISSUE THREAD

**Issue by lironzemingo** [segmentio/analytics_flutter#29]
How do I set a Firebase push token?

**Comment by edsonjab** [comment]
hi @lironzemingo , do yo mean about [this token](https://firebase.google.com/docs/cloud-messaging/flutter/client#access_the_registration_token) ?

**Comment by edsonjab** [comment]
You can follow that [URL](https://firebase.google.com/docs/cloud-messaging/flutter/client) (from firebase) they explain how implement in flutter, for your project,  you can include analytics_flutter methods like 'track' inside the message methods.

**Comment by edsonjab** [comment]
Hi @lironzemingo sorry for the delay, you can follow this test as example to set token on your context:
![image](https://github.com/segmentio/analytics_flutter/assets/22898327/af6925ab-f58d-4aed-95e8-7eee9b018b6b)
On line 36 you can access to set a new token value for your context.

**Comment by ggirotto** [comment]
@edsonjab this sounds a little bit hacky to set directly on the platform instance. There's no plugin function to do so?
