### ISSUE TITLE
AppsFlyer plugin issue

### ISSUE THREAD

**Issue by QoLTech** [segmentio/analytics_flutter#36]
I am having trouble adding the AppsFlyerDestination plugin. Anytime I call .track() with data, I get an exception here.

`[OTTO::ERROR::LOGGER] Exception -> type 'Null' is not a subtype of type 'bool'
[OTTO::ERROR::LOGGER] #0      extractRevenue
utils.dart:2
#1      AppsFlyerDestination.track
plugin_appsflyer.dart:93
#2      EventPlugin.execute
plugin.dart:54
#3      DestinationPlugin.process
plugin.dart:163
                        <asynchronous suspension>
`

I'm not passing revenue in with the properties and it fails even when I do.

Also, is there any information on how this integration works? Does it send directly to AppsFlyer, or does it process the event through the connection within Segment? My events don't have anything in the "integrations" field where previously we did when using the old flutter_segment package.

**Comment by edsonjab** [comment]
Hi @QoLTech thank you for your report, we start looking into this.

**Comment by QoLTech** [comment]
It looks like an issue with Utils.extractRevenue:2. You're checking the value of the item in the map by key when it looks like you're attempting to check if the value of the item in the map is null or not. I can get around this by passing 'revenue': false in the properties since that actually satisfies what the code is actually checking. The fix would be to change that line to `if (properties[key] == null) {`

**Comment by oscb** [comment]
Fix already merged
