### ISSUE TITLE
Can't add AppsFlyer integration

### ISSUE THREAD

**Issue by QoLTech** [segmentio/analytics_flutter#37]
I am having trouble adding an AppsFlyer integration. This is documented in the https://pub.dev/packages/flutter_segment package that we are migrating from. What is the equivalent to this solution using this package? https://pub.dev/packages/flutter_segment#setting-the-options-globally

I have tried doing analytics.state.integrations.addIntegration("AppsFlyer", {"appsFlyerId": "id"}), but it doesn't show up in the integrations field when I'm watching the stream of events coming in.

I have tried adding the AppsFlyer plugin by doing analytics.addPlugin(AppsFlyerDestination()) and I still don't see anything in the integrations field when I'm watching the stream of events coming in.

Can you provide any insight into how to accomplish this?

**Comment by edsonjab** [comment]
Hi @QoLTech thank you for your report, we start looking into this.

**Comment by QoLTech** [comment]
Adding the AppsFlyerDestination was all I needed to do as well as resolve the issue in https://github.com/segmentio/analytics_flutter/issues/36. The Segment events are displayed on the Segment site immediately, but AppsFlyer has some delay before showing the events. I understand now that this plugin is calling the AppsFlyer SDK directly instead of adding data to the Segment event to connect over to AppsFlyer.
