### ISSUE TITLE
Lifecycle events not sent

### ISSUE THREAD

**Issue by lironzemingo** [segmentio/analytics_flutter#42]
Hi,
I'm creating the client in the following way:
`    _analyticsClient = createClient(
        Configuration(FlavorHelper.getSegmentWriteKey(), trackApplicationLifecycleEvents: true, debug: kDebugMode));`
but lifecycle events are not sent properly. only "Application Opened" is sent on app launch, but not "Application Installed"  or "Application Backgrounded" .
why is this happening? is the configuration right? 

Tested on an Android Samsung S22, Android 13 OS.

**Comment by edsonjab** [comment]
Hi @lironzemingo thank you for your report, we start looking into this.

**Comment by QoLTech** [comment]
I also don't get Application Installed events.

**Comment by lironzemingo** [comment]
@edsonjab I think I figured it out. in createClient:
```
Analytics createClient(Configuration configuration) {
  if (configuration.debug) {
    Analytics.debug = true;
  }
  if (configuration.flushPolicies == null) {
    configuration = setFlushPolicies(configuration, defaultFlushPolicies);
  }

  final analytics = Analytics(configuration, storeFactory());

  if (configuration.debug) {
    analytics.addPlugin(EventLogger());
  }

  analytics.init();
  ScreenObserver().screenStream.listen((name) {
    analytics.screen(name);
  });

  return analytics;
}
```

you're initializing and persisting the `ContextState` in the creation of the `Analytics()` object.
then, you're calling `analytics.init() `-> `_checkInstalledVersion()` -> 
`    if (previousContext == null) {
      track("Application Installed", properties: {
        "version": context.app.version,
        "build": context.app.build,
      });
    } `
 but previousContext will never be null, because it was persisted before, so "Application Installed" will never be tracked.

**Comment by QuirijnGB** [comment]
When is this being merged into main? Currently sitting in a branch
