### ISSUE TITLE
No podspec

### ISSUE THREAD

**Issue by devmobile-vulog** [segmentio/analytics_flutter#59]
Hi,

We are facing an issue when trying to implement IDFA plugin : 
`[!] No podspec found for 'segment_analytics_plugin_idfa' in '.symlinks/plugins/segment_analytics_plugin_idfa/ios'`

Maybe there is a mistake on the configuration of the podspec on your side ?

Thank you for investigating.

**Comment by edsonjab** [comment]
Hi @devmobile-vulog  thank you for your report. We start looking into this.

**Comment by edsonjab** [comment]
hi @devmobile-vulog sorry to answer late:
You can use this configuration on you `pubspec.yaml`:
![image](https://github.com/segmentio/analytics_flutter/assets/22898327/5fe49290-f9b7-431c-84de-14575d9ae64d)

And you can call like this on your code:
![image](https://github.com/segmentio/analytics_flutter/assets/22898327/ffec2281-63ef-4889-9a20-d4d2bdbc7553)

**Comment by devmobile-vulog** [comment]
Hi @edsonjab 
It works fine, thank you.
However, now i am not able to apply the IDFA Plugin to the analytics client instance. When trying to call `addPlugin(PluginIdfa())` method, i am faced to this error :
`The argument type 'PluginIdfa' can't be assigned to the parameter type 'Plugin'`

Maybe i am missing something about the configuration. 
The documentation says : Follow the [instructions for adding plugins](https://github.com/segmentio/analytics_flutter_#adding-plugins) on the main Analytics client but the url is not working anymore. 

Could you please provide the right url or tell me what i am missing please ?

Thank you !

**Comment by edsonjab** [comment]
Hi @devmobile-vulog this the new [URL](https://pub.dev/packages/segment_analytics#adding-plugins) with the instructions to add plugins.

**Comment by devmobile-vulog** [comment]
Hi @edsonjab ,

Thank you for providing the right url. Everything seems to be good on configurations side.
However, there is still an error when trying to add the plugin: it seems that there is a conflict on imports into the package, and an alias is missing for the 'plugin.dart' import into 'analytics.dart' class (I think there is a name conflit with another Plugin class) causing the following error :
`The argument type 'PluginIdfa' can't be assigned to the parameter type 'Plugin'`

Thank you !

**Comment by edsonjab** [comment]
Hi @devmobile-vulog you can add a cast on the line when you add your plugin 
`analytics.addPlugin(PluginIdfa() as Plugin);`

I have identified the problem, we will fix the issue.

**Comment by deepakg202** [comment]
Updating the podspec name to `segment_analytics_plugin_idfa` fixes this issue.
