### ISSUE TITLE
Missing macOS support (flutter_fgbg)

### ISSUE THREAD

**Issue by maxlapides** [segmentio/analytics_flutter#6]
When running in a macOS app, you'll get this error:

```
════════ Exception caught by services library ══════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel com.ajinasokan.flutter_fgbg/events:
MissingPluginException(No implementation found for method listen on channel com.ajinasokan.flutter_fgbg/events)
```

This is caused by the `flutter_fgbg` package, which doesn't currently support macOS. To resolve the issue, we could replace flutter_fgbg with `WidgetsBindingObserver` (on macOS only, or for all platforms).

**Comment by edsonjab** [comment]
Hi @maxlapides  thank you for your report, we start looking into this.

**Comment by MichaelGHSeg** [comment]
Sorry, issue got put on the wrong list, didn't intend to close this yet.
