### ISSUE TITLE
Map cast error

### ISSUE THREAD

**Issue by loganholgersson** [segmentio/analytics_flutter#61]
Hi Segment team. Could you take a look and fix the next issue we are facing in production builds:

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: type '_Map<Object?, Object?>' is not a subtype 
of type 'Map<String, dynamic>' in type cast at AnalyticsPlatformImpl.linkStream.<fn>(analytics_pigeon.dart:21)
```

https://github.com/segmentio/analytics_flutter/blob/b7123b5ac2545f97146641a534e0be29b0117393/packages/core/lib/analytics_pigeon.dart#L21

Thanks!

**Comment by edsonjab** [comment]
Hi @loganholgersson thank you for your report. We start looking into this.

**Comment by Imgkl** [comment]
@edsonjab I see a PR has been merged to main, calling it as fix. So it's safe to assume that this is closed?

**Comment by edsonjab** [comment]
@Imgkl yes, this issue will be closed.
