### ISSUE TITLE
Question: anonymous id update on identify call

### ISSUE THREAD

**Issue by ZPGC** [segmentio/analytics_flutter#62]
Hi, I just want to verify if it is an expected behaviour that an anonymous ID is being updated after calling identify. 

In the docs, anonymousId is saved in the user’s cookie, as well as localStorage, and will stick with that user until the cache is cleared or a reset call is triggered.

Thank you.

**Comment by edsonjab** [comment]
Hi @ZPGC, sorry to answer late,
This is an expected behaviour [HERE](https://pub.dev/packages/segment_analytics#identify) is the link with the documentation.
