### ISSUE TITLE
[Unit Test Case] Missing from Example app

### ISSUE THREAD

**Issue by hemandroid24k** [segmentio/analytics_flutter#67]
Hey team,

For example app code repo, we have the functions of analytics.track() and analytics.identify(). However, there was a lack of unit test cases for the event tracking. Can we expect any working example references for unit test cases for the respective code?

**Comment by edsonjab** [comment]
hi @hemandroid24k, we are working on creating the unit test for the code. [Here](https://github.com/segmentio/analytics_flutter/tree/main/packages/core/test) is an example for some test.

**Comment by hemandroid24k** [comment]
Hey @edsonjab Thanks for your response. But the example that you referring to is for the package-level code, but not belongs to the actual implementation. Is there any ETA for the example app unit test cases?

**Comment by edsonjab** [comment]
hi @hemandroid24k we still working on the unit test for the code.
