### ISSUE TITLE
How to Prevent Saving Files in Documents Directory with segment_analytics

### ISSUE THREAD

**Issue by suysoftware** [segmentio/analytics_flutter#68]
Hi,
I am currently developing a Flutter desktop application and utilizing your segment_analytics package. I have noticed that the package is automatically saving files in the documents directory (please see attached screenshot for reference).

For my application's use case, I would prefer not to have these files saved in the user's documents directory. Could you please guide me on how I can disable this behavior? Is there a configuration option or a method within the package that allows me to block the saving of these files?

![Screenshot 2024-03-31 at 00 07 17](https://github.com/segmentio/analytics_flutter/assets/78134326/1eab2076-6a88-4d27-a7f1-8a932e2c1300)

**Comment by edsonjab** [comment]
Hi @suysoftware, [here](https://github.com/segmentio/analytics_flutter/blob/main/CONTRIBUTING.md#json-code-generation) is the explanation about the reason for those files.

**Comment by suysoftware** [comment]
@edsonjab  But you should add option for choose direction or disable. Because I got a lot of report about these files in my app. These files syncing with iCloud all times. You should choose . (hidden folder) for these. Because hidden files is not syncing with iCloud

**Comment by edsonjab** [comment]
hi @suysoftware we start looking into your this.
