### ISSUE TITLE
Please downgrade http dependency to 0.13.6

### ISSUE THREAD

**Issue by lukeshan-ctm** [segmentio/analytics_flutter#7]
http 1.0.0 require dart 3 while this analytics_flutter only require dart 2.19 in pubspec.

http 1.0.0 and http 0.13.6 are same except the dart version requirement.

Please downgrade http to 0.13.6 so dart 2.19 users (like us) can use this analytics_flutter.

Thanks.

**Comment by tylersavery** [comment]
I created this fork (untested at this time but fixed the dependency issue)

https://github.com/tylersavery/analytics_flutter
