### ISSUE TITLE
Add token to context

### ISSUE THREAD

**Issue by dtlucho** [segmentio/analytics_flutter#71]
I would like to know if the is any way to add the device token to the context. In the package created by a community member there was a way to do so, and I don't seem to find a way to do it with this package.

Here you can find the documentation from said package https://github.com/la-haus/flutter-segment?tab=readme-ov-file#sending-device-tokens-strings-for-push-notifications.

**Comment by edsonjab** [comment]
hi @dtlucho thank you for your report, we start looking into this.
