### ISSUE TITLE
If event upload fails, try to upload the event again

### ISSUE THREAD

**Issue by Jay-57blocks** [segmentio/analytics_flutter#72]
Since I am developing the LOT project, most of the time it interacts with hardware devices and cannot access the Internet. I want to monitor the availability of the network and let it upload all events. My current code is like this. Is there a more recommended way to write it?

```dart

   _connectivity.onConnectivityChanged.listen((event) {
      final accessNetwork = event == ConnectivityResult.mobile;
      _onAccessNetworkChanged(accessNetwork);
  });

 void _onAccessNetworkChanged(bool accessNetwork) {
    if (accessNetwork) {
      _analytics.addFlushPolicy([ImmediatelyFlushPolicy()]);
    } else {
      _analytics.removeFlushPolicy(_analytics.getFlushPolicies());
    }
  }


class ImmediatelyFlushPolicy extends FlushPolicy {
  @override
  start() {
    shouldFlush = true;
  }
}

```

I found that if uploading an event fails, it will not retransmit the event. Is there any way to upload the event again? Or can you know whether each event was uploaded successfully and re-upload these events through custom code?

<img width="1463" alt="image" src="https://github.com/segmentio/analytics_flutter/assets/132547846/6b679c50-04ac-4b4e-87e0-9ac92fb59a9e">

**Comment by edsonjab** [comment]
Hi @Jay-57blocks you can create your own plugin or policy to identify that part of process, you can check our documentation about that [HERE](https://pub.dev/packages/segment_analytics#plugins--timeline-architecture)
