### ISSUE TITLE
ErrorLoadingStorage

### ISSUE THREAD

**Issue by cerealexx** [segmentio/analytics_flutter#80]
Lately we've been spammed with these errors in iOS devices from Segment plugin:
```
ErrorLoadingStorage state.dart in PersistedState.init.<fn>
Error loading storage: FormatException: Unexpected character (at character 13)
{"queue":[]}anonymousId":"ff3b23a3-d9b9-42cf-be59-5574cf37da38","messageId"...
```
Any ideas?

**Comment by edsonjab** [comment]
hi @cerealexx we are working on the solution, thank you for your report.

**Comment by edsonjab** [comment]
hi @cerealexx could you help me to show me your configuration to try replicate the issue, please?

**Comment by cerealexx** [comment]
```
Configuration(
  WRITE_KEY,
  trackApplicationLifecycleEvents: true,
)
```

**Comment by PabloTortosaLopez** [comment]
Hey, I'm getting the same error, any updates on this?

**Comment by edsonjab** [comment]
Hi @PabloTortosaLopez , could you help us with the configuration of your project to know how can we replicate the issue?
Or an example similar to your project and configuration, please?

**Comment by PabloTortosaLopez** [comment]
Hey @edsonjab, this is the configuration that we are using on the project, pretty straightforward.

```
Configuration(
                _platformKey
                trackApplicationLifecycleEvents: true,
              )
```

We are using `segment_analytics: ^1.0.1` and `flutter 3.22.2`

**Comment by brunosp15** [comment]
I'm facing the same problem, do you have any update on this?

We are using `segment_analytics: 1.0.2` and `flutter 3.22.1`

**Comment by fhdeodato** [comment]
Hey guys,

I am facing the same trouble

![image](https://github.com/user-attachments/assets/740b8ed9-076c-4b76-927d-70c59ed85db8)

not sure if there is an workaround for that, it is really hard to replicate... not get the error while debugging yet =(

**Comment by felipefuzaro-funda** [comment]
I see the PR is merged, thank you for that 😄

Do you have a plan to release a new plugin version?

**Comment by PabloTortosaLopez** [comment]
Hey! I see the PR with the fix is merged 🚀

When will a new version with this fix be released?

Thank you!

**Comment by 0aps** [comment]
@edsonjab any clue when we'll have a new version that includes this fix?
