### ISSUE TITLE
IP addresses are missing from events

### ISSUE THREAD

**Issue by maxlapides** [segmentio/analytics_flutter#82]
Hi there, we've been trying to get IP addresses stamped on our Segment events, but so far we have not been successful. All events coming from this package do not have an IP address on them, as we can see in the segment.com Debugger.

I noticed that there is a previous issue, that seems to have already resolved this issue: https://github.com/segmentio/analytics_flutter/issues/43#issuecomment-1997825449. But, we still haven't seen any IP addresses.

@oscb Do you have any additional information on IP addresses? Is there any change required on our side, or is there something that needs to be adjusted on Segment? Thank you!

**Comment by MichaelGHSeg** [comment]
I'm looking into this.  I'll try to get you an update or a fix soon.

**Comment by MichaelGHSeg** [comment]
A fix should be deployed early next week.

**Comment by MichaelGHSeg** [comment]
Should be working now, let us know if you have any further issues.

**Comment by maxlapides** [comment]
Thank you @MichaelGHSeg!
