### ISSUE TITLE
AppsflyerSdk `getAppsFlyerUID` Support.

### ISSUE THREAD

**Issue by Imgkl** [segmentio/analytics_flutter#88]
Need a way to get the `getAppsFlyerUID` from the SDK when Appsflyer is added as a plugin.

**Comment by edsonjab** [comment]
Thank you for your report, we start looking into your request.

**Comment by edsonjab** [comment]
Hi @Imgkl sorry to answer late.
You can try this code to use the method `getAppsFlyerUID`, before you need to initialize the parameters `AppsFlyerDestination()` with your settings of `AppsFlyerSettings` 

![image](https://github.com/segmentio/analytics_flutter/assets/22898327/56815892-f9db-4423-a977-096e1ca3b1b8)
