### ISSUE TITLE
Shouldnt `Product Clicked` event be mapped as `select_item` instead of `select_content`?

### ISSUE THREAD

**Issue by fhdeodato** [segmentio/analytics_flutter#90]
Hello,

thanks for the amazing plugin =) 

I was reviewing the Firebase integration and looks like the plugin translates the event `Product Clicked` to Firebase `select_content` one.

but we have a recommended events when the user clicks a product that is the `select_item`.

Which makes think that we should change it because, since the event is specific for "Products".

this event already exists in the firebase package

https://github.com/firebase/flutterfire/blob/master/packages/firebase_analytics/firebase_analytics/lib/src/firebase_analytics.dart#L828

Is there any reason that is mapped using the `select_content`? it is important to know before sending a PR

Thanks for the help

**Comment by edsonjab** [comment]
Hi @fhdeodato thank you for your report, looks like we have a mistake on that method, it makes sense that the `Product Clicked` will be `select_item`.
