### ISSUE TITLE
Segment Traits Override for MixPanel?

### ISSUE THREAD

**Issue by Michaelpwoo** [segmentio/analytics_flutter#92]
Hi,

We've been using the key word `company` to set the user's company name in MixPanel (prior to using this SDK). We are now using this SDK and I was wondering if it's possible to still keep the data the same? The data that is being set in MixPanel from this SDK is `company:{"name":"Fake, Inc."}`. Is it possible to override it and match our previous data of `company:Fake, Inc.`?

Thanks,

**Comment by edsonjab** [comment]
Hi @Michaelpwoo sorry to answer late, I didn't get your issue.

You can set a company on the group method like [this example](https://pub.dev/packages/segment_analytics#group).

And exist another object on UserTraits that exist the company object with diferent attributes. Like [this example](https://segment.com/docs/connections/spec/identify/#traits:~:text=User%E2%80%99s%20birthday-,company,-Object).

could you help us with an example about your issue please?
